version: '3'

 
services:
  nextjs:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    image: back2basic/kendy-nextjs:latest
    ports:
      - 3000:3000
    # stdin_open: true
    networks:
      - default
    restart: unless-stopped